---

# Location-specific settings
api_server_ip:            "10.0.20.20"
api_server_hostname:      "alpha-api.global.corp"
aws_subnet_id:            "{{ alpha_subnet_id }}"
aws_subnet_name:          "Alpha Subnet"