---

# Location-specific settings
api_server_ip:            "10.0.20.25"
api_server_hostname:      "beta01.global.corp.domain"
aws_subnet_id:            "{{ beta_subnet_id }}"
aws_subnet_name:          "Beta Subnet"