---

# Location-specific settings
api_server_ip:            "10.0.30.25"
api_server_hostname:      "alpha-api.global.corp"
aws_subnet_id:            "{{ beta_subnet_id }}"
aws_subnet_name:          "Beta Subnet"