---

# Location-specific settings
api_server_ip:            "10.100.40.25"
api_server_hostname:      "delta01.global.corp.domain"
aws_subnet_id:            "{{ delta_subnet_id }}"
aws_subnet_name:          "Delta Subnet"